WITH LASTDAY AS (
SELECT CONCAT(USERS.IMSI,USERS.IMEI) as IMSI_IMEI, USERS.IMEI, TER.TER_MODEL_NAME, CELL_ID
FROM
(SELECT IMSI,  IMEI , MAX(CONCAT(MCC,MNC,LAC,CI,SAC,ECI)) AS CELL_ID
FROM PS.detail_ufdr_other_17062
WHERE SUBSTR(IMSI,1,5) = '23801'
GROUP BY IMSI, IMEI
)USERS
,PS.DIM_TERMINAL TER
WHERE USERS.IMEI = TER.TAC
	 AND TER.TER_MODEL_NAME LIKE  ('%iPhone 7%') ),

HH0800 AS (
SELECT CONCAT(USERS.IMSI,USERS.IMEI) as IMSI_IMEI, USERS.IMEI, TER.TER_MODEL_NAME, CELL_ID
FROM
(SELECT IMSI,  IMEI, MAX(CONCAT(MCC,MNC,LAC,CI,SAC,ECI))  AS CELL_ID 
FROM PS.detail_ufdr_other_17063
WHERE SUBSTR(IMSI,1,5) = '23801'
     AND from_unixtime((BEGIN_TIME - (BEGIN_TIME % 3600))+2*3600,'yyyy-MM-dd HH:mm') <= '2016-09-19 09:00'
GROUP BY IMSI, IMEI
)USERS
,PS.DIM_TERMINAL TER
WHERE USERS.IMEI = TER.TAC
	 AND TER.TER_MODEL_NAME LIKE  ('%iPhone 7%') ),

HH0900 AS (
SELECT CONCAT(USERS.IMSI,USERS.IMEI) as IMSI_IMEI, USERS.IMEI, TER.TER_MODEL_NAME, CELL_ID
FROM
(SELECT IMSI,  IMEI, MAX(CONCAT(MCC,MNC,LAC,CI,SAC,ECI))  AS CELL_ID 
FROM PS.detail_ufdr_other_17063
WHERE SUBSTR(IMSI,1,5) = '23801'
     AND from_unixtime((BEGIN_TIME - (BEGIN_TIME % 3600))+2*3600,'yyyy-MM-dd HH:mm') <= '2016-09-19 10:00'
GROUP BY IMSI, IMEI
)USERS
,PS.DIM_TERMINAL TER
WHERE USERS.IMEI = TER.TAC
	 AND TER.TER_MODEL_NAME LIKE  ('%iPhone 7%') ) ,

HH1000 AS (
SELECT CONCAT(USERS.IMSI,USERS.IMEI) as IMSI_IMEI, USERS.IMEI, TER.TER_MODEL_NAME, CELL_ID
FROM
(SELECT IMSI,  IMEI, MAX(CONCAT(MCC,MNC,LAC,CI,SAC,ECI))  AS CELL_ID 
FROM PS.detail_ufdr_other_17063
WHERE SUBSTR(IMSI,1,5) = '23801'
     AND from_unixtime((BEGIN_TIME - (BEGIN_TIME % 3600))+2*3600,'yyyy-MM-dd HH:mm') <= '2016-09-19 11:00'
GROUP BY IMSI, IMEI
)USERS
,PS.DIM_TERMINAL TER
WHERE USERS.IMEI = TER.TAC
	 AND TER.TER_MODEL_NAME LIKE  ('%iPhone 7%') ) ,

HH1100 AS (
SELECT CONCAT(USERS.IMSI,USERS.IMEI) as IMSI_IMEI, USERS.IMEI, TER.TER_MODEL_NAME, CELL_ID
FROM
(SELECT IMSI,  IMEI, MAX(CONCAT(MCC,MNC,LAC,CI,SAC,ECI))  AS CELL_ID 
FROM PS.detail_ufdr_other_17063
WHERE SUBSTR(IMSI,1,5) = '23801'
     AND from_unixtime((BEGIN_TIME - (BEGIN_TIME % 3600))+2*3600,'yyyy-MM-dd HH:mm') <= '2016-09-19 12:00'
GROUP BY IMSI, IMEI
)USERS
,PS.DIM_TERMINAL TER
WHERE USERS.IMEI = TER.TAC
	 AND TER.TER_MODEL_NAME LIKE  ('%iPhone 7%') ) ,

HH1200 AS (
SELECT CONCAT(USERS.IMSI,USERS.IMEI) as IMSI_IMEI, USERS.IMEI, TER.TER_MODEL_NAME, CELL_ID
FROM
(SELECT IMSI,  IMEI, MAX(CONCAT(MCC,MNC,LAC,CI,SAC,ECI))  AS CELL_ID  
FROM PS.detail_ufdr_other_17063
WHERE SUBSTR(IMSI,1,5) = '23801'
     AND from_unixtime((BEGIN_TIME - (BEGIN_TIME % 3600))+2*3600,'yyyy-MM-dd HH:mm') <= '2016-09-19 13:00'
GROUP BY IMSI, IMEI
)USERS
,PS.DIM_TERMINAL TER
WHERE USERS.IMEI = TER.TAC
	 AND TER.TER_MODEL_NAME LIKE  ('%iPhone 7%') ) ,

HH1300 AS (
SELECT CONCAT(USERS.IMSI,USERS.IMEI) as IMSI_IMEI, USERS.IMEI, TER.TER_MODEL_NAME, CELL_ID
FROM
(SELECT IMSI,  IMEI, MAX(CONCAT(MCC,MNC,LAC,CI,SAC,ECI))  AS CELL_ID  
FROM PS.detail_ufdr_other_17063
WHERE SUBSTR(IMSI,1,5) = '23801'
     AND from_unixtime((BEGIN_TIME - (BEGIN_TIME % 3600))+2*3600,'yyyy-MM-dd HH:mm') <= '2016-09-19 14:00'
GROUP BY IMSI, IMEI
)USERS
,PS.DIM_TERMINAL TER
WHERE USERS.IMEI = TER.TAC
	 AND TER.TER_MODEL_NAME LIKE  ('%iPhone 7%') ) ,

HH1400 AS (
SELECT CONCAT(USERS.IMSI,USERS.IMEI) as IMSI_IMEI, USERS.IMEI, TER.TER_MODEL_NAME, CELL_ID
FROM
(SELECT IMSI,  IMEI, MAX(CONCAT(MCC,MNC,LAC,CI,SAC,ECI))  AS CELL_ID  
FROM PS.detail_ufdr_other_17063
WHERE SUBSTRING(IMSI,1,5) = '23801'
     AND from_unixtime((BEGIN_TIME - (BEGIN_TIME % 3600))+2*3600,'yyyy-MM-dd HH:mm') <= '2016-09-19 15:00'
GROUP BY IMSI, IMEI
)USERS
,PS.DIM_TERMINAL TER
WHERE USERS.IMEI = TER.TAC
	 AND TER.TER_MODEL_NAME LIKE  ('%iPhone 7%') ) ,

HH1500 AS (
SELECT CONCAT(USERS.IMSI,USERS.IMEI) as IMSI_IMEI, USERS.IMEI, TER.TER_MODEL_NAME, CELL_ID
FROM
(SELECT IMSI,  IMEI, MAX(CONCAT(MCC,MNC,LAC,CI,SAC,ECI))  AS CELL_ID  
FROM PS.detail_ufdr_other_17063
WHERE SUBSTRING(IMSI,1,5) = '23801'
     AND from_unixtime((BEGIN_TIME - (BEGIN_TIME % 3600))+2*3600,'yyyy-MM-dd HH:mm') <= '2016-09-19 16:00'
GROUP BY IMSI, IMEI
)USERS
,PS.DIM_TERMINAL TER
WHERE USERS.IMEI = TER.TAC
	 AND TER.TER_MODEL_NAME LIKE  ('%iPhone 7%') ) ,

HH1600 AS (
SELECT CONCAT(USERS.IMSI,USERS.IMEI) as IMSI_IMEI, USERS.IMEI, TER.TER_MODEL_NAME, CELL_ID
FROM
(SELECT IMSI,  IMEI, MAX(CONCAT(MCC,MNC,LAC,CI,SAC,ECI))  AS CELL_ID  
FROM PS.detail_ufdr_other_17063
WHERE SUBSTRING(IMSI,1,5) = '23801'
     AND from_unixtime((BEGIN_TIME - (BEGIN_TIME % 3600))+2*3600,'yyyy-MM-dd HH:mm') <= '2016-09-19 17:00'
GROUP BY IMSI, IMEI
)USERS
,PS.DIM_TERMINAL TER
WHERE USERS.IMEI = TER.TAC
	 AND TER.TER_MODEL_NAME LIKE  ('%iPhone 7%') ) ,

HH1700 AS (
SELECT CONCAT(USERS.IMSI,USERS.IMEI) as IMSI_IMEI, USERS.IMEI, TER.TER_MODEL_NAME, CELL_ID
FROM
(SELECT IMSI,  IMEI, MAX(CONCAT(MCC,MNC,LAC,CI,SAC,ECI))  AS CELL_ID  
FROM PS.detail_ufdr_other_17063
WHERE SUBSTRING(IMSI,1,5) = '23801'
     AND from_unixtime((BEGIN_TIME - (BEGIN_TIME % 3600))+2*3600,'yyyy-MM-dd HH:mm') <= '2016-09-19 18:00'
GROUP BY IMSI, IMEI
)USERS
,PS.DIM_TERMINAL TER
WHERE USERS.IMEI = TER.TAC
	 AND TER.TER_MODEL_NAME LIKE  ('%iPhone 7%') ) ,

HH1800 AS (
SELECT CONCAT(USERS.IMSI,USERS.IMEI) as IMSI_IMEI, USERS.IMEI, TER.TER_MODEL_NAME, CELL_ID
FROM
(SELECT IMSI,  IMEI, MAX(CONCAT(MCC,MNC,LAC,CI,SAC,ECI))  AS CELL_ID  
FROM PS.detail_ufdr_other_17063
WHERE SUBSTRING(IMSI,1,5) = '23801'
     AND from_unixtime((BEGIN_TIME - (BEGIN_TIME % 3600))+2*3600,'yyyy-MM-dd HH:mm') <= '2016-09-19 19:00'
GROUP BY IMSI, IMEI
)USERS
,PS.DIM_TERMINAL TER
WHERE USERS.IMEI = TER.TAC
	 AND TER.TER_MODEL_NAME LIKE  ('%iPhone 7%') ) 

SELECT INCR_NUM_BY_HR.SERVICETIME
,SUBSTR(INCR_NUM_BY_HR.IMSI_IMEI,1,LENGTH(INCR_NUM_BY_HR.IMSI_IMEI)-LENGTH(INCR_NUM_BY_HR.IMEI)) AS IMSI
,INCR_NUM_BY_HR.IMEI
,INCR_NUM_BY_HR.TER_MODEL_NAME
,CGI.CELL_ID
,CGI.CELL_NAME
FROM(
SELECT "2016-09-19 09:00" AS SERVICETIME, HH0900.*
FROM HH0900
LEFT JOIN 
	(SELECT *
	 FROM LASTDAY
	 UNION ALL
	 SELECT *
	 FROM HH0800) LAST_HH0800
	 ON LAST_HH0800.IMSI_IMEI = HH0900.IMSI_IMEI
WHERE LAST_HH0800.IMSI_IMEI IS NULL
 
UNION ALL
SELECT "2016-09-19 10:00" AS SERVICETIME, HH1000.*
FROM HH1000
LEFT JOIN 
	(SELECT *
	 FROM LASTDAY
	 UNION ALL
	 SELECT *
	 FROM HH0900) LAST_HH0900
	 ON LAST_HH0900.IMSI_IMEI = HH1000.IMSI_IMEI
WHERE LAST_HH0900.IMSI_IMEI IS NULL

UNION ALL
SELECT "2016-09-19 11:00" AS SERVICETIME, HH1100.*
FROM HH1100
LEFT JOIN 
	(SELECT *
	 FROM LASTDAY
	 UNION ALL
	 SELECT *
	 FROM HH1000) LAST_HH1000
	 ON LAST_HH1000.IMSI_IMEI = HH1100.IMSI_IMEI
WHERE LAST_HH1000.IMSI_IMEI IS NULL

UNION ALL
SELECT "2016-09-19 12:00" AS SERVICETIME, HH1200.*
FROM HH1200
LEFT JOIN 
	(SELECT *
	 FROM LASTDAY
	 UNION ALL
	 SELECT *
	 FROM HH1100) LAST_HH1100
	 ON LAST_HH1100.IMSI_IMEI = HH1200.IMSI_IMEI
WHERE LAST_HH1100.IMSI_IMEI IS NULL

UNION ALL
SELECT "2016-09-19 13:00" AS SERVICETIME, HH1300.*
FROM HH1300
LEFT JOIN 
	(SELECT *
	 FROM LASTDAY
	 UNION ALL
	 SELECT *
	 FROM HH1200) LAST_HH1200
	 ON LAST_HH1200.IMSI_IMEI = HH1300.IMSI_IMEI
WHERE LAST_HH1200.IMSI_IMEI IS NULL

UNION ALL
SELECT "2016-09-19 14:00" AS SERVICETIME, HH1400.*
FROM HH1400
LEFT JOIN 
	(SELECT *
	 FROM LASTDAY
	 UNION ALL
	 SELECT *
	 FROM HH1300) LAST_HH1300
	 ON LAST_HH1300.IMSI_IMEI = HH1400.IMSI_IMEI
WHERE LAST_HH1300.IMSI_IMEI IS NULL

UNION ALL
SELECT "2016-09-19 15:00" AS SERVICETIME, HH1500.*
FROM HH1500
LEFT JOIN 
	(SELECT *
	 FROM LASTDAY
	 UNION ALL
	 SELECT *
	 FROM HH1400) LAST_HH1400
	 ON LAST_HH1400.IMSI_IMEI = HH1500.IMSI_IMEI
WHERE LAST_HH1400.IMSI_IMEI IS NULL

UNION ALL
SELECT "2016-09-19 16:00" AS SERVICETIME, HH1600.*
FROM HH1600
LEFT JOIN 
	(SELECT *
	 FROM LASTDAY
	 UNION ALL
	 SELECT *
	 FROM HH1500) LAST_HH1500
	 ON LAST_HH1500.IMSI_IMEI = HH1600.IMSI_IMEI
WHERE LAST_HH1500.IMSI_IMEI IS NULL

UNION ALL
SELECT "2016-09-19 17:00" AS SERVICETIME, HH1700.*
FROM HH1700
LEFT JOIN 
	(SELECT *
	 FROM LASTDAY
	 UNION ALL
	 SELECT *
	 FROM HH1600) LAST_HH1600
	 ON LAST_HH1600.IMSI_IMEI = HH1700.IMSI_IMEI
WHERE LAST_HH1600.IMSI_IMEI IS NULL

UNION ALL
SELECT "2016-09-19 18:00" AS SERVICETIME, HH1800.*
FROM HH1800
LEFT JOIN 
	(SELECT *
	 FROM LASTDAY
	 UNION ALL
	 SELECT *
	 FROM HH1700) LAST_HH1700
	 ON LAST_HH1700.IMSI_IMEI = HH1800.IMSI_IMEI
WHERE LAST_HH1700.IMSI_IMEI IS NULL
) INCR_NUM_BY_HR

JOIN(SELECT CONCAT(MCC,MNC,LAC,CI) AS CELL_ID, CI_NAME AS CELL_NAME
FROM PS.CFG_CGI
UNION ALL
SELECT CONCAT(MCC,MNC,LAC,SAC) AS CELL_ID, SAC_NAME AS CELL_NAME
FROM PS.CFG_SAI
UNION ALL
SELECT CONCAT(MCC,MNC,ECI) AS CELL_ID, ECI_NAME AS CELL_NAME
FROM PS.CFG_ECGI
) CGI ON CGI.CELL_ID = INCR_NUM_BY_HR.CELL_ID

LIMIT 10000;
