WITH LASTWEEK AS (
SELECT TER.TER_OS_TYPE_NAME,TER.TER_BRAND_NAME,TER.TER_MODEL_NAME, USERS.IMSI+USERS.IMEI as IMSI_IMEI, USERS.IMEI
FROM(
SELECT IMSI, TAC AS IMEI
FROM PS.SDR_FLOW_BASE_USER_1DAY_560
WHERE MCC = '238'
        AND MNC = '01'
		AND CAST(DATEADD(hh,CAST(STARTTIME/3600 AS INT),'19700101 02:00:00') AS DATE) >= '09/05/2016'
	    AND CAST(DATEADD(hh,CAST(STARTTIME/3600 AS INT),'19700101 02:00:00') AS DATE) < '09/12/2016'
GROUP BY IMSI, TAC
)USERS
,PS.DIM_TERMINAL TER
WHERE USERS.IMEI = TER.TAC
     AND TER.TER_TYPE_ID = 0
GROUP BY TER.TER_OS_TYPE_NAME,TER.TER_BRAND_NAME,TER.TER_MODEL_NAME, USERS.IMSI+USERS.IMEI,USERS.IMEI
),

THISWEEK AS (
SELECT TER.TER_OS_TYPE_NAME,TER.TER_BRAND_NAME,TER.TER_MODEL_NAME, USERS.IMSI+USERS.IMEI as IMSI_IMEI,USERS.IMEI--, USERS.PROT_CATEGORY, USERS.LAYER2ID
FROM(
SELECT IMSI,TAC AS IMEI
FROM PS.SDR_FLOW_BASE_USER_1DAY_560
WHERE MCC = '238'
        AND MNC = '01'
		AND CAST(DATEADD(hh,CAST(STARTTIME/3600 AS INT),'19700101 02:00:00') AS DATE) >= '09/12/2016'
	    AND CAST(DATEADD(hh,CAST(STARTTIME/3600 AS INT),'19700101 02:00:00') AS DATE) < '09/14/2016'
GROUP BY IMSI, TAC
)USERS
,PS.DIM_TERMINAL TER
WHERE USERS.IMEI = TER.TAC
	 AND TER.TER_MODEL_NAME LIKE ('%IPHONE 6S%') -- including 'IPHONE 6S PLUS'
GROUP BY TER.TER_OS_TYPE_NAME,TER.TER_BRAND_NAME,TER.TER_MODEL_NAME, USERS.IMSI+USERS.IMEI,USERS.IMEI
) 

SELECT count(*) AS SHIFT_NUM
,LASTWEEK_OS,THISWEEK_OS
,LASTWEEK_BARND,THISWEEK_BRAND
,LASTWEEK_MODEL,THISWEEK_MODEL
FROM(
SELECT THISWEEK.IMSI_IMEI AS IMSI_IMEI_THISWEEK
,LASTWEEK.TER_OS_TYPE_NAME AS  LASTWEEK_OS
,THISWEEK.TER_OS_TYPE_NAME AS THISWEEK_OS
,LASTWEEK.TER_BRAND_NAME AS LASTWEEK_BARND
,THISWEEK.TER_BRAND_NAME AS THISWEEK_BRAND
,LASTWEEK.TER_MODEL_NAME AS LASTWEEK_MODEL
,THISWEEK.TER_MODEL_NAME AS THISWEEK_MODEL
FROM THISWEEK,LASTWEEK
WHERE SUBSTRING(LASTWEEK.IMSI_IMEI,1,LENGTH(LASTWEEK.IMSI_IMEI)-LENGTH(LASTWEEK.IMEI)) = SUBSTRING(THISWEEK.IMSI_IMEI,1,LENGTH(THISWEEK.IMSI_IMEI)-LENGTH(THISWEEK.IMEI))
      AND LASTWEEK.IMEI <> THISWEEK.IMEI	
GROUP BY THISWEEK.IMSI_IMEI
,LASTWEEK.TER_OS_TYPE_NAME,THISWEEK.TER_OS_TYPE_NAME
,LASTWEEK.TER_BRAND_NAME,THISWEEK.TER_BRAND_NAME
,LASTWEEK.TER_MODEL_NAME,THISWEEK.TER_MODEL_NAME
) SH_NUM
GROUP BY LASTWEEK_OS,THISWEEK_OS
,LASTWEEK_BARND,THISWEEK_BRAND
,LASTWEEK_MODEL,THISWEEK_MODEL
ORDER BY count(*)  DESC
;COMMIT;




